### ISSUE TITLE
PredictStructures "--pass options"

### ISSUE THREAD

**Issue by thielwh** [ui-icts/aptamer-web#3]
When using predict structures, how does the “--pass options” work? The script fails whenever I use pass-through options (e.g. -T 37)

**Comment by chrisortman** [comment]
@thielwh  I tried running the script manually with pass options

```
➜  python predict_structures.py -v 2 --pass_options "-T 37" ./Final_Rd12.fa
##################
Running RNAFold...
##################
Command: RNAfold  -T 37
['AAACAUGCAUCAUCAGGUAAGUACGGUCCC', '..((.(((........))).))........ ( -0.90)', '']

Error parsing RNAfold output. (Couldn't find statistics.) Please check RNAfold options.
```

And it generated an error. I can dig it, but sharing it in case the error message tells you more than it tells me

**Comment by thielwh** [comment]
This might refer to the program trying to generate summary statistics for different structural properties. Either parsing the structure statistics of each sequence into a comma delimited file or calculating a mean and SEM of all the structures.

**Comment by chrisortman** [comment]
This is should be working on the aws box now.
If you don't specify -p to RNAFold then it won't calculate statistics, so I add it if it isn't present.
